// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_everythings_better_in_black_and_white = "CgkI1OrHq90TEAIQBw"; // <GPGSID>
        public const string achievement_taking_a_jog = "CgkI1OrHq90TEAIQAw"; // <GPGSID>
        public const string achievement_and_penguin_kind = "CgkI1OrHq90TEAIQAg"; // <GPGSID>
        public const string leaderboard_highest_of_the_high_scores = "CgkI1OrHq90TEAIQCA"; // <GPGSID>
        public const string achievement_feel_the_burn = "CgkI1OrHq90TEAIQBQ"; // <GPGSID>
        public const string achievement_for_the_north_pole = "CgkI1OrHq90TEAIQAQ"; // <GPGSID>
        public const string achievement_into_the_night = "CgkI1OrHq90TEAIQBg"; // <GPGSID>
        public const string achievement_steadying_the_pace = "CgkI1OrHq90TEAIQBA"; // <GPGSID>
        public const string leaderboard_doggies_and_rodents_blasted = "CgkI1OrHq90TEAIQCQ"; // <GPGSID>

}

